In [130]:
function my_Gale_Shap{T<:Int64}(m_prefs::AbstractArray{T, 2}, f_prefs::AbstractArray{T, 2})
    m = size(m_prefs, 2)
    n = size(f_prefs, 2)
    m_matched = zeros(Int64, m)
    f_matched = zeros(Int64, n)
    for t in 1:(n+1)
        for i in 1:m
            if m_matched[i] == 0
                if m_prefs[t, i] == 0
                    m_matched[i] = 0
                else
                    if f_matched[m_prefs[t, i]] == 0
                        f_matched[m_prefs[t, i]] = i
                        m_matched[i] = m_prefs[t, i]
                        elseif (f_matched[m_prefs[t, i]] != i) && (findnext(f_prefs[:, m_prefs[t, i]], f_matched[m_prefs[t, i]], 1) > findnext(f_prefs[:, m_prefs[t, i]], i, 1))
                        m_matched[f_matched[m_prefs[t, i]]] = 0
                        f_matched[m_prefs[t, i]] = i
                        m_matched[i] = m_prefs[t, i]
                    else
                        f_matched[m_prefs[t, i]] = f_matched[m_prefs[t, i]]
                        m_matched[i] = m_matched[i]
                    end
                end
            else
                m_matched[i] = m_matched[i]
            end
        end
    end
    return m_matched, f_matched
end

my_Gale_Shap (generic function with 1 method)

In [131]:
m_prefs = [1 2 0 3; 3 2 1 0; 1 2 0 3]'

4x3 Array{Int64,2}:
 1  3  1
 2  2  2
 0  1  0
 3  0  3

In [132]:
size(m_prefs, 2)

3

In [133]:
f_prefs = [1 2 3 0; 2 0 1 3; 2 3 0 1]'

4x3 Array{Int64,2}:
 1  2  2
 2  0  3
 3  1  0
 0  3  1

In [134]:
size(f_prefs, 2)

3

In [135]:
my_Gale_Shap(m_prefs, f_prefs)

([1,3,2],[1,3,2])

In [16]:
z = Array(Int64, 4, 3)

4x3 Array{Int64,2}:
 34359738376  0  0
  2147483649  0  0
           0  0  0
           0  0  0

In [11]:
length(z[:, 1])

4

In [4]:
range(z)

LoadError: LoadError: MethodError: `range` has no method matching range(::Array{Float64,2})
Closest candidates are:
  range{T}(::T, !Matched::Integer)
  range{T,S}(::T, !Matched::S, !Matched::Integer)
while loading In[4], in expression starting on line 1

In [17]:
zeros(4)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [18]:
z[1, 1]

34359738376

In [21]:
find(6)

1-element Array{Int64,1}:
 1

In [34]:
?findnext

search: findnext



```
findnext(A, v, i)
```

Find the next index >= `i` of an element of `A` equal to `v` (using `==`), or `0` if not found.

```
findnext(predicate, A, i)
```

Find the next index >= `i` of an element of `A` for which `predicate` returns `true`, or `0` if not found.

```
findnext(A, i)
```

Find the next index >= `i` of a non-zero element of `A`, or `0` if not found.


In [25]:
w = [-1, -2, 2]

3-element Array{Int64,1}:
 -1
 -2
  2

In [44]:
findnext(w, -1, 3)

0

In [45]:
?None

search: nonzeros count_ones leading_ones @noinline trailing_ones print_joined



No documentation found.

`Base.None` is of type `Union`:

**Summary:**

```julia
immutable Union <: Type{T}
```

**Fields:**

```julia
types :: SimpleVector
```


Union{} instead.
  likely near In[45]:119


In [14]:
?size

search: size sizeof sizehint sizehint! Csize_t resize! filesize Cssize_t



```
size(A, [dim...])
```

Returns a tuple containing the dimensions of `A`. Optionally you can specify the dimension(s) you want the length of, and get the length of that dimension, or a tuple of the lengths of dimensions you asked for.:

```
julia> A = rand(2,3,4);

julia> size(A, 2)
3

julia> size(A,3,2)
(4,3)
```


In [35]:
convert(Int, zeros(4))

LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{Int64}, ::Array{Float64,1})
This may have arisen from a call to the constructor Int64(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{Int64}, !Matched::Int8)
  convert(::Type{Int64}, !Matched::UInt8)
  ...
while loading In[35], in expression starting on line 1

In [45]:
?BoundsError

search: BoundsError



```
BoundsError([a],[i])
```

An indexing operation into an array, `a`, tried to access an out-of-bounds element, `i`.


In [88]:
?pop!

search: pop! popdisplay apropos deepcopy precompile __precompile__ peakflops



```
pop!(collection, key[, default])
```

Delete and return the mapping for `key` if it exists in `collection`, otherwise return `default`, or throw an error if default is not specified.

```
pop!(collection) -> item
```

Remove the last item in `collection` and return it.

```jldoctest
julia> A=[1, 2, 3, 4, 5, 6]
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

julia> pop!(A)
6

julia> A
5-element Array{Int64,1}:
 1
 2
 3
 4
 5
```


In [92]:
?minimum

search: minimum minimum! DimensionMismatch



```
minimum(A, dims)
```

Compute the minimum value of an array over the given dimensions.

```
minimum(itr)
```

Returns the smallest element in a collection.


In [93]:
?findmin

search: findmin findmax



```
findmin(A, dims) -> (minval, index)
```

For an array input, returns the value and index of the minimum over the given dimensions.

```
findmin(itr) -> (x, index)
```

Returns the minimum element and its index.


In [107]:
z = [2, 0, 3]
find(z)

2-element Array{Int64,1}:
 1
 3

In [109]:
?findlast

search: findlast find_library



```
findlast(A, v)
```

Return the index of the last element equal to `v` in `A`.

```
findlast(A)
```

Return the index of the last non-zero value in `A` (determined by `A[i]!=0`).

```
findlast(predicate, A)
```

Return the index of the last element of `A` for which `predicate` returns `true`.


In [129]:
?elseif

search: elseif



`if`-`elseif`-`else` performs conditional evaluation, which allows portions of code to be evaluated or not evaluated depending on the value of a boolean expression. Here is the anatomy of the `if`-`elseif`-`else` conditional syntax:

```
if x < y
    println("x is less than y")
elseif x > y
    println("x is greater than y")
else
    println("x is equal to y")
end
```

If the condition expression `x < y` is true, then the corresponding block is evaluated; otherwise the condition expression `x > y` is evaluated, and if it is true, the corresponding block is evaluated; if neither expression is true, the `else` block is evaluated. The `elseif` and `else` blocks are optional, and as many `elseif` blocks as desired can be used.


In [1]:
?collect

search: collect Collections



```
collect(collection)
```

Return an array of all items in a collection. For associative collections, returns Pair{KeyType, ValType}.

```
collect(element_type, collection)
```

Return an array of type `Array{element_type,1}` of all items in a collection.


In [5]:
z = collect(1:4)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [4]:
?pop!

search: pop! popdisplay apropos deepcopy precompile __precompile__ peakflops



```
pop!(collection, key[, default])
```

Delete and return the mapping for `key` if it exists in `collection`, otherwise return `default`, or throw an error if default is not specified.

```
pop!(collection) -> item
```

Remove the last item in `collection` and return it.

```jldoctest
julia> A=[1, 2, 3, 4, 5, 6]
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

julia> pop!(A)
6

julia> A
5-element Array{Int64,1}:
 1
 2
 3
 4
 5
```


In [6]:
pop!(z)

4

In [7]:
pop!(z)

3

In [8]:
push!(z, 3)

3-element Array{Int64,1}:
 1
 2
 3

In [9]:
z

3-element Array{Int64,1}:
 1
 2
 3