In [105]:
function my_Gale_Shap{T<:Int64}(prop_prefs::AbstractArray{T, 2}, resp_prefs::AbstractArray{T, 2}, caps=ones(Int64, size(resp_prefs, 2)))
    m = size(prop_prefs, 2)
    n = size(resp_prefs, 2)
    L = sum(caps)
    prop_matched = zeros(Int64, m)
    resp_matched = zeros(Int64, L)
    prop_pool = collect(1:m)
    
    println(prop_matched, resp_matched, prop_pool, caps, 1)
    
    while length(prop_pool) != 0
        i = pop!(prop_pool)
        
        for j in prop_prefs[:, i]
            
            if j == 0
                prop_matched[i] = 0
                break
                
                println(prop_matched, resp_matched, prop_pool, 2)
                
                elseif j == 1
                count = 0
                k = 1
                l = caps[1]
                
                for t in k:l
                    if findnext(resp_prefs[:, j], resp_matched[t], 1) > findnext(resp_prefs[:, j], i, 1)
                        if resp_matched[t] == 0
                            resp_matched[t] = i
                            prop_matched[i] = j
                            count = 1
                            break
                            
                            println(prop_matched, resp_matched, prop_pool, 3)
                            
                        else
                            push!(prop_pool, resp_matched[t])
                            resp_matched[t] = i
                            prop_matched[i] = j
                            count = 1
                            break
                            
                            println(prop_matched, resp_matched, prop_pool, 4)
                            
                        end
                    else
                        resp_matched[t] = resp_matched[t]
                        prop_matched[i] = prop_matched[i]
                    end
                    
                    println(prop_matched, resp_matched, prop_pool, 5)
                    
                end
                if count == 1
                    break
                end
                
            else
                count = 0
                k = sum(caps[1:j-1]) + 1
                l = sum(caps[1:j])
                for t in k:l
                    if findnext(resp_prefs[:, j], resp_matched[t], 1) > findnext(resp_prefs[:, j], i, 1)
                        if resp_matched[t] == 0
                            resp_matched[t] = i
                            prop_matched[i] = j
                            count = 1
                            break
                            
                            println(prop_matched, resp_matched, prop_pool, 6)
                            
                        else
                            push!(prop_pool, resp_matched[t])
                            resp_matched[t] = i
                            prop_matched[i] = j
                            count = 1
                            break
                            
                            println(prop_matched, resp_matched, prop_pool, 7)
                            
                        end
                    else
                        resp_matched[t] = resp_matched[t]
                        prop_matched[i] = prop_matched[i]
                    end
                    
                    println(prop_matched, resp_matched, prop_pool, 8)
                    
                end
                if count == 1
                    break
                end
            end
        end
        
        println(prop_matched, resp_matched, prop_pool, 9)
        
    end
    return prop_matched, resp_matched
end

my_Gale_Shap (generic function with 2 methods)

In [106]:
prop_prefs = [0 1 2; 1 2 0; 2 0 1]

3x3 Array{Int64,2}:
 0  1  2
 1  2  0
 2  0  1

In [107]:
resp_prefs = [2 3; 0 2; 1 0; 3 1]

4x2 Array{Int64,2}:
 2  3
 0  2
 1  0
 3  1

In [108]:
my_Gale_Shap(prop_prefs, resp_prefs)

[0,0,0][0,0][1,2,3][1,1]1
[0,0,2][0,3][1,2]9
[0,1,2][2,3][1]9
[0,1,2][2,3]Int64[]9


([0,1,2],[2,3])

In [84]:
?break

search: break BufferStream AbstractVecOrMat AbstractSparseArray



`break` breaks out of a loop immediately. For example

```
i = 0
while true
    i += 1
    i > 10 && break
    println(i)
end
```

prints the numbers 1 to 10.


In [1]:
?cumsum

search: cumsum cumsum! cumsum_kbn



```rst
..  cumsum(A, [dim])

Cumulative sum along a dimension ``dim`` (defaults to 1).
See also :func:`cumsum!` to use a preallocated output array,
both for performance and to control the precision of the
output (e.g. to avoid overflow).
```


In [1]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [18]:
a = [1; 2; 3]

3-element Array{Int64,1}:
 1
 2
 3

In [19]:
pop!(a, 2)

LoadError: LoadError: MethodError: `pop!` has no method matching pop!(::Array{Int64,1}, ::Int64)
Closest candidates are:
  pop!(::Array{T,1})
  pop!(!Matched::IntSet, ::Integer)
  pop!(!Matched::IntSet, ::Integer, !Matched::Any)
  ...
while loading In[19], in expression starting on line 1

In [4]:
cumsum(a[2])

LoadError: LoadError: MethodError: `cumsum` has no method matching cumsum(::Int64)
while loading In[4], in expression starting on line 1

In [5]:
?cumsum_kbn

search: cumsum_kbn



```
cumsum_kbn(A, [dim])
```

Cumulative sum along a dimension, using the Kahan-Babuska-Neumaier compensated summation algorithm for additional accuracy. The dimension defaults to 1.


In [7]:
cumsum(a, 2)

1x3 Array{Int64,2}:
 1  3  6

In [9]:
?sum

search: sum sum! sumabs summary sumabs2 sumabs! sum_kbn sumabs2! cumsum cumsum!



```
sum(A, dims)
```

Sum elements of an array over the given dimensions.

```
sum(itr)
```

Returns the sum of all elements in a collection.

```
sum(f, itr)
```

Sum the results of calling function `f` on each element of `itr`.


In [10]:
?itr

search: itrunc bitrand UnitRange istriu istril Intrinsics IntrinsicFunction

Couldn't find itr
Perhaps you meant Ptr, bits, int, int8, im, in, inf, inv, is, isa, if or cor


LoadError: LoadError: "itr" is not defined in module Main
while loading In[10], in expression starting on line 119

In [5]:
sum(1:0)

0

In [11]:
sum(b[1]:b[1])

4

In [14]:
?pop!

search: pop! popdisplay apropos deepcopy precompile __precompile__ peakflops



```
pop!(collection, key[, default])
```

Delete and return the mapping for `key` if it exists in `collection`, otherwise return `default`, or throw an error if default is not specified.

```
pop!(collection) -> item
```

Remove the last item in `collection` and return it.

```jldoctest
julia> A=[1, 2, 3, 4, 5, 6]
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

julia> pop!(A)
6

julia> A
5-element Array{Int64,1}:
 1
 2
 3
 4
 5
```


In [53]:
b = [4; 5; 6]

3-element Array{Int64,1}:
 4
 5
 6

In [2]:
 deleteat!(b, findin(b, 5))

2-element Array{Int64,1}:
 4
 6

In [54]:
for i in 2:2
    b[i] = 1
end

In [62]:
b[2]

1

In [63]:
l = sum(b[1]:b[2])

0

In [57]:
k

5

In [58]:
l

0

In [64]:
a = b'

1x3 Array{Int64,2}:
 4  1  6

In [71]:
l = sum(b[1:2])

5

In [69]:
?cumsum

search: cumsum cumsum! cumsum_kbn



```rst
..  cumsum(A, [dim])

Cumulative sum along a dimension ``dim`` (defaults to 1).
See also :func:`cumsum!` to use a preallocated output array,
both for performance and to control the precision of the
output (e.g. to avoid overflow).
```


In [1]:
?Matrix

search: Matrix BitMatrix DenseMatrix SparseMatrix SharedMatrix SparseMatrixCSC



No documentation found.

`Base.Matrix` is of type `TypeConstructor`:

**Summary:**

```julia
immutable TypeConstructor <: Type{T}
```

**Fields:**

```julia
parameters :: SimpleVector
body       :: Any
```
