In [11]:
function my_Gale_Shap{T<:Int64}(prop_prefs::AbstractArray{T, 2}, resp_prefs::AbstractArray{T, 2}, caps=ones(T, size(resp_prefs, 2)))
    m, n = size(prop_prefs, 2), size(resp_prefs, 2)
    L = sum(caps)
    prop_matched = zeros(Int64, m)
    resp_matched = zeros(Int64, L)
    prop_pool = collect(1:m)
    
    while length(prop_pool) != 0
        i = pop!(prop_pool)
            
        for j in prop_prefs[:, i]
            if j == 0
                prop_matched[i] = 0
                break
                
            elseif j == 1
                
                k = 1
                l = caps[1]
                for t in k:l
                        
                    if findnext(resp_prefs[:, j], resp_matched[t], 1) > findnext(resp_prefs[:, j], i, 1)
                        if resp_matched[t] == 0
                            resp_matched[t] = i
                            prop_matched[i] = j
                            break
                                
                        else
                            push!(prop_pool, resp_matched[t])
                            resp_matched[t] = i
                            prop_matched[i] = j
                            break
                        end
                    end
                        
                end
                
            else
                k = sum(caps[1]:caps[j-1]) + 1
                l = sum(caps[1]:caps[j])
                for t in k:l
                        
                if findnext(resp_prefs[:, j], resp_matched[t], 1) > findnext(resp_prefs[:, j], i, 1)
                        if resp_matched[t] == 0
                            resp_matched[t] = i
                            prop_matched[i] = j
                            break
                                
                        else
                            push!(prop_pool, resp_matched[t])
                            count = 1
                            resp_matched[t] = i
                            prop_matched[i] = j
                            break
                        end
                    end
                        
                end
            end
        end
    end
    return prop_matched, resp_matched
end

my_Gale_Shap (generic function with 2 methods)

In [1]:
?cumsum

search: cumsum cumsum! cumsum_kbn



```rst
..  cumsum(A, [dim])

Cumulative sum along a dimension ``dim`` (defaults to 1).
See also :func:`cumsum!` to use a preallocated output array,
both for performance and to control the precision of the
output (e.g. to avoid overflow).
```


In [2]:
ones(Int64, 3)

3-element Array{Int64,1}:
 1
 1
 1

In [18]:
a = [1; 2; 3]

3-element Array{Int64,1}:
 1
 2
 3

In [19]:
pop!(a, 2)

LoadError: LoadError: MethodError: `pop!` has no method matching pop!(::Array{Int64,1}, ::Int64)
Closest candidates are:
  pop!(::Array{T,1})
  pop!(!Matched::IntSet, ::Integer)
  pop!(!Matched::IntSet, ::Integer, !Matched::Any)
  ...
while loading In[19], in expression starting on line 1

In [4]:
cumsum(a[2])

LoadError: LoadError: MethodError: `cumsum` has no method matching cumsum(::Int64)
while loading In[4], in expression starting on line 1

In [5]:
?cumsum_kbn

search: cumsum_kbn



```
cumsum_kbn(A, [dim])
```

Cumulative sum along a dimension, using the Kahan-Babuska-Neumaier compensated summation algorithm for additional accuracy. The dimension defaults to 1.


In [7]:
cumsum(a, 2)

1x3 Array{Int64,2}:
 1  3  6

In [9]:
?sum

search: sum sum! sumabs summary sumabs2 sumabs! sum_kbn sumabs2! cumsum cumsum!



```
sum(A, dims)
```

Sum elements of an array over the given dimensions.

```
sum(itr)
```

Returns the sum of all elements in a collection.

```
sum(f, itr)
```

Sum the results of calling function `f` on each element of `itr`.


In [10]:
?itr

search: itrunc bitrand UnitRange istriu istril Intrinsics IntrinsicFunction

Couldn't find itr
Perhaps you meant Ptr, bits, int, int8, im, in, inf, inv, is, isa, if or cor


LoadError: LoadError: "itr" is not defined in module Main
while loading In[10], in expression starting on line 119

In [5]:
sum(1:0)

0

In [8]:
sum(b[1]:b[0]) = 0

LoadError: LoadError: syntax: "b[1]:b[0]" is not a valid function argument name
while loading In[8], in expression starting on line 1

In [14]:
?pop!

search: pop! popdisplay apropos deepcopy precompile __precompile__ peakflops



```
pop!(collection, key[, default])
```

Delete and return the mapping for `key` if it exists in `collection`, otherwise return `default`, or throw an error if default is not specified.

```
pop!(collection) -> item
```

Remove the last item in `collection` and return it.

```jldoctest
julia> A=[1, 2, 3, 4, 5, 6]
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

julia> pop!(A)
6

julia> A
5-element Array{Int64,1}:
 1
 2
 3
 4
 5
```


In [1]:
b = [4; 5; 6]

3-element Array{Int64,1}:
 4
 5
 6

In [2]:
 deleteat!(b, findin(b, 5))

2-element Array{Int64,1}:
 4
 6